// Generated by gencpp from file ece642rtle/bumpEcho.msg
// DO NOT EDIT!


#ifndef ECE642RTLE_MESSAGE_BUMPECHO_H
#define ECE642RTLE_MESSAGE_BUMPECHO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ece642rtle
{
template <class ContainerAllocator>
struct bumpEcho_
{
  typedef bumpEcho_<ContainerAllocator> Type;

  bumpEcho_()
    : t()
    , x1(0)
    , y1(0)
    , x2(0)
    , y2(0)
    , resp(false)  {
    }
  bumpEcho_(const ContainerAllocator& _alloc)
    : t()
    , x1(0)
    , y1(0)
    , x2(0)
    , y2(0)
    , resp(false)  {
  (void)_alloc;
    }



   typedef ros::Time _t_type;
  _t_type t;

   typedef int32_t _x1_type;
  _x1_type x1;

   typedef int32_t _y1_type;
  _y1_type y1;

   typedef int32_t _x2_type;
  _x2_type x2;

   typedef int32_t _y2_type;
  _y2_type y2;

   typedef uint8_t _resp_type;
  _resp_type resp;




  typedef boost::shared_ptr< ::ece642rtle::bumpEcho_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ece642rtle::bumpEcho_<ContainerAllocator> const> ConstPtr;

}; // struct bumpEcho_

typedef ::ece642rtle::bumpEcho_<std::allocator<void> > bumpEcho;

typedef boost::shared_ptr< ::ece642rtle::bumpEcho > bumpEchoPtr;
typedef boost::shared_ptr< ::ece642rtle::bumpEcho const> bumpEchoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ece642rtle::bumpEcho_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ece642rtle::bumpEcho_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ece642rtle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ece642rtle': ['/home/student/catkin_ws/src/ece642rtle/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ece642rtle::bumpEcho_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ece642rtle::bumpEcho_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece642rtle::bumpEcho_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece642rtle::bumpEcho_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece642rtle::bumpEcho_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece642rtle::bumpEcho_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ece642rtle::bumpEcho_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f39b12694464cc7a7e355caf0f0ec3c";
  }

  static const char* value(const ::ece642rtle::bumpEcho_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f39b12694464cc7ULL;
  static const uint64_t static_value2 = 0xa7e355caf0f0ec3cULL;
};

template<class ContainerAllocator>
struct DataType< ::ece642rtle::bumpEcho_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ece642rtle/bumpEcho";
  }

  static const char* value(const ::ece642rtle::bumpEcho_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ece642rtle::bumpEcho_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time t\n\
int32 x1\n\
int32 y1\n\
int32 x2\n\
int32 y2\n\
bool resp\n\
\n\
";
  }

  static const char* value(const ::ece642rtle::bumpEcho_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ece642rtle::bumpEcho_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.t);
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.x2);
      stream.next(m.y2);
      stream.next(m.resp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bumpEcho_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ece642rtle::bumpEcho_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ece642rtle::bumpEcho_<ContainerAllocator>& v)
  {
    s << indent << "t: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.t);
    s << indent << "x1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x1);
    s << indent << "y1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y1);
    s << indent << "x2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x2);
    s << indent << "y2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y2);
    s << indent << "resp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.resp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ECE642RTLE_MESSAGE_BUMPECHO_H
