// Generated by gencpp from file ece642rtle/Kill.msg
// DO NOT EDIT!


#ifndef ECE642RTLE_MESSAGE_KILL_H
#define ECE642RTLE_MESSAGE_KILL_H

#include <ros/service_traits.h>


#include <ece642rtle/KillRequest.h>
#include <ece642rtle/KillResponse.h>


namespace ece642rtle
{

struct Kill
{

typedef KillRequest Request;
typedef KillResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Kill
} // namespace ece642rtle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ece642rtle::Kill > {
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::ece642rtle::Kill&) { return value(); }
};

template<>
struct DataType< ::ece642rtle::Kill > {
  static const char* value()
  {
    return "ece642rtle/Kill";
  }

  static const char* value(const ::ece642rtle::Kill&) { return value(); }
};


// service_traits::MD5Sum< ::ece642rtle::KillRequest> should match 
// service_traits::MD5Sum< ::ece642rtle::Kill > 
template<>
struct MD5Sum< ::ece642rtle::KillRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ece642rtle::Kill >::value();
  }
  static const char* value(const ::ece642rtle::KillRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ece642rtle::KillRequest> should match 
// service_traits::DataType< ::ece642rtle::Kill > 
template<>
struct DataType< ::ece642rtle::KillRequest>
{
  static const char* value()
  {
    return DataType< ::ece642rtle::Kill >::value();
  }
  static const char* value(const ::ece642rtle::KillRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ece642rtle::KillResponse> should match 
// service_traits::MD5Sum< ::ece642rtle::Kill > 
template<>
struct MD5Sum< ::ece642rtle::KillResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ece642rtle::Kill >::value();
  }
  static const char* value(const ::ece642rtle::KillResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ece642rtle::KillResponse> should match 
// service_traits::DataType< ::ece642rtle::Kill > 
template<>
struct DataType< ::ece642rtle::KillResponse>
{
  static const char* value()
  {
    return DataType< ::ece642rtle::Kill >::value();
  }
  static const char* value(const ::ece642rtle::KillResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ECE642RTLE_MESSAGE_KILL_H
