// Generated by gencpp from file ece642rtle/PoseOrntBundle.msg
// DO NOT EDIT!


#ifndef ECE642RTLE_MESSAGE_POSEORNTBUNDLE_H
#define ECE642RTLE_MESSAGE_POSEORNTBUNDLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ece642rtle
{
template <class ContainerAllocator>
struct PoseOrntBundle_
{
  typedef PoseOrntBundle_<ContainerAllocator> Type;

  PoseOrntBundle_()
    : t()
    , x(0)
    , y(0)
    , o(0)  {
    }
  PoseOrntBundle_(const ContainerAllocator& _alloc)
    : t()
    , x(0)
    , y(0)
    , o(0)  {
  (void)_alloc;
    }



   typedef ros::Time _t_type;
  _t_type t;

   typedef int8_t _x_type;
  _x_type x;

   typedef int8_t _y_type;
  _y_type y;

   typedef int8_t _o_type;
  _o_type o;




  typedef boost::shared_ptr< ::ece642rtle::PoseOrntBundle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ece642rtle::PoseOrntBundle_<ContainerAllocator> const> ConstPtr;

}; // struct PoseOrntBundle_

typedef ::ece642rtle::PoseOrntBundle_<std::allocator<void> > PoseOrntBundle;

typedef boost::shared_ptr< ::ece642rtle::PoseOrntBundle > PoseOrntBundlePtr;
typedef boost::shared_ptr< ::ece642rtle::PoseOrntBundle const> PoseOrntBundleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ece642rtle::PoseOrntBundle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ece642rtle::PoseOrntBundle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ece642rtle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ece642rtle': ['/home/student/catkin_ws/src/ece642rtle/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ece642rtle::PoseOrntBundle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ece642rtle::PoseOrntBundle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece642rtle::PoseOrntBundle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece642rtle::PoseOrntBundle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece642rtle::PoseOrntBundle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece642rtle::PoseOrntBundle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ece642rtle::PoseOrntBundle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4bf56cff2846ddf0c7c3fbc294b28115";
  }

  static const char* value(const ::ece642rtle::PoseOrntBundle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4bf56cff2846ddf0ULL;
  static const uint64_t static_value2 = 0xc7c3fbc294b28115ULL;
};

template<class ContainerAllocator>
struct DataType< ::ece642rtle::PoseOrntBundle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ece642rtle/PoseOrntBundle";
  }

  static const char* value(const ::ece642rtle::PoseOrntBundle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ece642rtle::PoseOrntBundle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time t\n\
int8 x\n\
int8 y\n\
int8 o\n\
";
  }

  static const char* value(const ::ece642rtle::PoseOrntBundle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ece642rtle::PoseOrntBundle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.t);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.o);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseOrntBundle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ece642rtle::PoseOrntBundle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ece642rtle::PoseOrntBundle_<ContainerAllocator>& v)
  {
    s << indent << "t: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.t);
    s << indent << "x: ";
    Printer<int8_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int8_t>::stream(s, indent + "  ", v.y);
    s << indent << "o: ";
    Printer<int8_t>::stream(s, indent + "  ", v.o);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ECE642RTLE_MESSAGE_POSEORNTBUNDLE_H
