// Generated by gencpp from file ece642rtle/RTIatendResponse.msg
// DO NOT EDIT!


#ifndef ECE642RTLE_MESSAGE_RTIATENDRESPONSE_H
#define ECE642RTLE_MESSAGE_RTIATENDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ece642rtle
{
template <class ContainerAllocator>
struct RTIatendResponse_
{
  typedef RTIatendResponse_<ContainerAllocator> Type;

  RTIatendResponse_()
    : atend(false)  {
    }
  RTIatendResponse_(const ContainerAllocator& _alloc)
    : atend(false)  {
  (void)_alloc;
    }



   typedef uint8_t _atend_type;
  _atend_type atend;




  typedef boost::shared_ptr< ::ece642rtle::RTIatendResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ece642rtle::RTIatendResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RTIatendResponse_

typedef ::ece642rtle::RTIatendResponse_<std::allocator<void> > RTIatendResponse;

typedef boost::shared_ptr< ::ece642rtle::RTIatendResponse > RTIatendResponsePtr;
typedef boost::shared_ptr< ::ece642rtle::RTIatendResponse const> RTIatendResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ece642rtle::RTIatendResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ece642rtle::RTIatendResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ece642rtle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ece642rtle': ['/home/student/catkin_ws/src/ece642rtle/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ece642rtle::RTIatendResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ece642rtle::RTIatendResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece642rtle::RTIatendResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece642rtle::RTIatendResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece642rtle::RTIatendResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece642rtle::RTIatendResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ece642rtle::RTIatendResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74eb9cd583cb224ce5e6427d11f6cad3";
  }

  static const char* value(const ::ece642rtle::RTIatendResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74eb9cd583cb224cULL;
  static const uint64_t static_value2 = 0xe5e6427d11f6cad3ULL;
};

template<class ContainerAllocator>
struct DataType< ::ece642rtle::RTIatendResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ece642rtle/RTIatendResponse";
  }

  static const char* value(const ::ece642rtle::RTIatendResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ece642rtle::RTIatendResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool atend\n\
\n\
";
  }

  static const char* value(const ::ece642rtle::RTIatendResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ece642rtle::RTIatendResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.atend);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RTIatendResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ece642rtle::RTIatendResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ece642rtle::RTIatendResponse_<ContainerAllocator>& v)
  {
    s << indent << "atend: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.atend);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ECE642RTLE_MESSAGE_RTIATENDRESPONSE_H
