// Generated by gencpp from file ece642rtle/RTIatend.msg
// DO NOT EDIT!


#ifndef ECE642RTLE_MESSAGE_RTIATEND_H
#define ECE642RTLE_MESSAGE_RTIATEND_H

#include <ros/service_traits.h>


#include <ece642rtle/RTIatendRequest.h>
#include <ece642rtle/RTIatendResponse.h>


namespace ece642rtle
{

struct RTIatend
{

typedef RTIatendRequest Request;
typedef RTIatendResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RTIatend
} // namespace ece642rtle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ece642rtle::RTIatend > {
  static const char* value()
  {
    return "601274b2c558d8c19960f10fd7863a32";
  }

  static const char* value(const ::ece642rtle::RTIatend&) { return value(); }
};

template<>
struct DataType< ::ece642rtle::RTIatend > {
  static const char* value()
  {
    return "ece642rtle/RTIatend";
  }

  static const char* value(const ::ece642rtle::RTIatend&) { return value(); }
};


// service_traits::MD5Sum< ::ece642rtle::RTIatendRequest> should match
// service_traits::MD5Sum< ::ece642rtle::RTIatend >
template<>
struct MD5Sum< ::ece642rtle::RTIatendRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ece642rtle::RTIatend >::value();
  }
  static const char* value(const ::ece642rtle::RTIatendRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ece642rtle::RTIatendRequest> should match
// service_traits::DataType< ::ece642rtle::RTIatend >
template<>
struct DataType< ::ece642rtle::RTIatendRequest>
{
  static const char* value()
  {
    return DataType< ::ece642rtle::RTIatend >::value();
  }
  static const char* value(const ::ece642rtle::RTIatendRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ece642rtle::RTIatendResponse> should match
// service_traits::MD5Sum< ::ece642rtle::RTIatend >
template<>
struct MD5Sum< ::ece642rtle::RTIatendResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ece642rtle::RTIatend >::value();
  }
  static const char* value(const ::ece642rtle::RTIatendResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ece642rtle::RTIatendResponse> should match
// service_traits::DataType< ::ece642rtle::RTIatend >
template<>
struct DataType< ::ece642rtle::RTIatendResponse>
{
  static const char* value()
  {
    return DataType< ::ece642rtle::RTIatend >::value();
  }
  static const char* value(const ::ece642rtle::RTIatendResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ECE642RTLE_MESSAGE_RTIATEND_H
