// Generated by gencpp from file ece642rtle/RTIbumpResponse.msg
// DO NOT EDIT!


#ifndef ECE642RTLE_MESSAGE_RTIBUMPRESPONSE_H
#define ECE642RTLE_MESSAGE_RTIBUMPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ece642rtle
{
template <class ContainerAllocator>
struct RTIbumpResponse_
{
  typedef RTIbumpResponse_<ContainerAllocator> Type;

  RTIbumpResponse_()
    : bump(false)  {
    }
  RTIbumpResponse_(const ContainerAllocator& _alloc)
    : bump(false)  {
  (void)_alloc;
    }



   typedef uint8_t _bump_type;
  _bump_type bump;




  typedef boost::shared_ptr< ::ece642rtle::RTIbumpResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ece642rtle::RTIbumpResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RTIbumpResponse_

typedef ::ece642rtle::RTIbumpResponse_<std::allocator<void> > RTIbumpResponse;

typedef boost::shared_ptr< ::ece642rtle::RTIbumpResponse > RTIbumpResponsePtr;
typedef boost::shared_ptr< ::ece642rtle::RTIbumpResponse const> RTIbumpResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ece642rtle::RTIbumpResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ece642rtle::RTIbumpResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ece642rtle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ece642rtle': ['/home/student/catkin_ws/src/ece642rtle/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ece642rtle::RTIbumpResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ece642rtle::RTIbumpResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece642rtle::RTIbumpResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece642rtle::RTIbumpResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece642rtle::RTIbumpResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece642rtle::RTIbumpResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ece642rtle::RTIbumpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "735dfbbb79e16ebcd80b369cfbea8d63";
  }

  static const char* value(const ::ece642rtle::RTIbumpResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x735dfbbb79e16ebcULL;
  static const uint64_t static_value2 = 0xd80b369cfbea8d63ULL;
};

template<class ContainerAllocator>
struct DataType< ::ece642rtle::RTIbumpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ece642rtle/RTIbumpResponse";
  }

  static const char* value(const ::ece642rtle::RTIbumpResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ece642rtle::RTIbumpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool bump\n\
";
  }

  static const char* value(const ::ece642rtle::RTIbumpResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ece642rtle::RTIbumpResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bump);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RTIbumpResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ece642rtle::RTIbumpResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ece642rtle::RTIbumpResponse_<ContainerAllocator>& v)
  {
    s << indent << "bump: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bump);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ECE642RTLE_MESSAGE_RTIBUMPRESPONSE_H
