// Generated by gencpp from file ece642rtle/RTIbump.msg
// DO NOT EDIT!


#ifndef ECE642RTLE_MESSAGE_RTIBUMP_H
#define ECE642RTLE_MESSAGE_RTIBUMP_H

#include <ros/service_traits.h>


#include <ece642rtle/RTIbumpRequest.h>
#include <ece642rtle/RTIbumpResponse.h>


namespace ece642rtle
{

struct RTIbump
{

typedef RTIbumpRequest Request;
typedef RTIbumpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RTIbump
} // namespace ece642rtle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ece642rtle::RTIbump > {
  static const char* value()
  {
    return "572d9da764261393a9c6c33976c42dac";
  }

  static const char* value(const ::ece642rtle::RTIbump&) { return value(); }
};

template<>
struct DataType< ::ece642rtle::RTIbump > {
  static const char* value()
  {
    return "ece642rtle/RTIbump";
  }

  static const char* value(const ::ece642rtle::RTIbump&) { return value(); }
};


// service_traits::MD5Sum< ::ece642rtle::RTIbumpRequest> should match 
// service_traits::MD5Sum< ::ece642rtle::RTIbump > 
template<>
struct MD5Sum< ::ece642rtle::RTIbumpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ece642rtle::RTIbump >::value();
  }
  static const char* value(const ::ece642rtle::RTIbumpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ece642rtle::RTIbumpRequest> should match 
// service_traits::DataType< ::ece642rtle::RTIbump > 
template<>
struct DataType< ::ece642rtle::RTIbumpRequest>
{
  static const char* value()
  {
    return DataType< ::ece642rtle::RTIbump >::value();
  }
  static const char* value(const ::ece642rtle::RTIbumpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ece642rtle::RTIbumpResponse> should match 
// service_traits::MD5Sum< ::ece642rtle::RTIbump > 
template<>
struct MD5Sum< ::ece642rtle::RTIbumpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ece642rtle::RTIbump >::value();
  }
  static const char* value(const ::ece642rtle::RTIbumpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ece642rtle::RTIbumpResponse> should match 
// service_traits::DataType< ::ece642rtle::RTIbump > 
template<>
struct DataType< ::ece642rtle::RTIbumpResponse>
{
  static const char* value()
  {
    return DataType< ::ece642rtle::RTIbump >::value();
  }
  static const char* value(const ::ece642rtle::RTIbumpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ECE642RTLE_MESSAGE_RTIBUMP_H
