// Generated by gencpp from file ece642rtle/Spawn.msg
// DO NOT EDIT!


#ifndef ECE642RTLE_MESSAGE_SPAWN_H
#define ECE642RTLE_MESSAGE_SPAWN_H

#include <ros/service_traits.h>


#include <ece642rtle/SpawnRequest.h>
#include <ece642rtle/SpawnResponse.h>


namespace ece642rtle
{

struct Spawn
{

typedef SpawnRequest Request;
typedef SpawnResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Spawn
} // namespace ece642rtle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ece642rtle::Spawn > {
  static const char* value()
  {
    return "0b2d2e872a8e2887d5ed626f2bf2c561";
  }

  static const char* value(const ::ece642rtle::Spawn&) { return value(); }
};

template<>
struct DataType< ::ece642rtle::Spawn > {
  static const char* value()
  {
    return "ece642rtle/Spawn";
  }

  static const char* value(const ::ece642rtle::Spawn&) { return value(); }
};


// service_traits::MD5Sum< ::ece642rtle::SpawnRequest> should match
// service_traits::MD5Sum< ::ece642rtle::Spawn >
template<>
struct MD5Sum< ::ece642rtle::SpawnRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ece642rtle::Spawn >::value();
  }
  static const char* value(const ::ece642rtle::SpawnRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ece642rtle::SpawnRequest> should match
// service_traits::DataType< ::ece642rtle::Spawn >
template<>
struct DataType< ::ece642rtle::SpawnRequest>
{
  static const char* value()
  {
    return DataType< ::ece642rtle::Spawn >::value();
  }
  static const char* value(const ::ece642rtle::SpawnRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ece642rtle::SpawnResponse> should match
// service_traits::MD5Sum< ::ece642rtle::Spawn >
template<>
struct MD5Sum< ::ece642rtle::SpawnResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ece642rtle::Spawn >::value();
  }
  static const char* value(const ::ece642rtle::SpawnResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ece642rtle::SpawnResponse> should match
// service_traits::DataType< ::ece642rtle::Spawn >
template<>
struct DataType< ::ece642rtle::SpawnResponse>
{
  static const char* value()
  {
    return DataType< ::ece642rtle::Spawn >::value();
  }
  static const char* value(const ::ece642rtle::SpawnResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ECE642RTLE_MESSAGE_SPAWN_H
