// Generated by gencpp from file ece642rtle/timeInt8.msg
// DO NOT EDIT!


#ifndef ECE642RTLE_MESSAGE_TIMEINT8_H
#define ECE642RTLE_MESSAGE_TIMEINT8_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ece642rtle
{
template <class ContainerAllocator>
struct timeInt8_
{
  typedef timeInt8_<ContainerAllocator> Type;

  timeInt8_()
    : t()
    , data(0)  {
    }
  timeInt8_(const ContainerAllocator& _alloc)
    : t()
    , data(0)  {
  (void)_alloc;
    }



   typedef ros::Time _t_type;
  _t_type t;

   typedef int8_t _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::ece642rtle::timeInt8_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ece642rtle::timeInt8_<ContainerAllocator> const> ConstPtr;

}; // struct timeInt8_

typedef ::ece642rtle::timeInt8_<std::allocator<void> > timeInt8;

typedef boost::shared_ptr< ::ece642rtle::timeInt8 > timeInt8Ptr;
typedef boost::shared_ptr< ::ece642rtle::timeInt8 const> timeInt8ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ece642rtle::timeInt8_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ece642rtle::timeInt8_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ece642rtle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ece642rtle': ['/home/student/catkin_ws/src/ece642rtle/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ece642rtle::timeInt8_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ece642rtle::timeInt8_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece642rtle::timeInt8_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece642rtle::timeInt8_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece642rtle::timeInt8_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece642rtle::timeInt8_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ece642rtle::timeInt8_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ab6d0dd70600c3c29e7123d70261d97";
  }

  static const char* value(const ::ece642rtle::timeInt8_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ab6d0dd70600c3cULL;
  static const uint64_t static_value2 = 0x29e7123d70261d97ULL;
};

template<class ContainerAllocator>
struct DataType< ::ece642rtle::timeInt8_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ece642rtle/timeInt8";
  }

  static const char* value(const ::ece642rtle::timeInt8_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ece642rtle::timeInt8_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time t\n\
int8 data\n\
";
  }

  static const char* value(const ::ece642rtle::timeInt8_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ece642rtle::timeInt8_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.t);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct timeInt8_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ece642rtle::timeInt8_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ece642rtle::timeInt8_<ContainerAllocator>& v)
  {
    s << indent << "t: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.t);
    s << indent << "data: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ECE642RTLE_MESSAGE_TIMEINT8_H
